"""Claude Code integration utilities."""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional


@dataclass(frozen=True)
class ClaudeIntegration:
    """Class-based Claude Code integration."""

    def is_available(self) -> bool:
        """Return True when the Claude Code CLI is installed."""
        return shutil.which("claude") is not None

    def setup(
        self,
        workspace_root: Path,
        interaction_path: Optional[Path],
        emit_project_config: bool,
    ) -> Path:
        """Write Claude Code settings and optional project config assets."""
        settings_path = self.ensure_workspace_settings(
            workspace_root,
            interaction_path,
            emit_project_config,
        )
        if emit_project_config:
            self.emit_project_config(workspace_root, interaction_path)
        return settings_path

    def launch(
        self,
        workspace_root: Path,
        interaction_path: Optional[Path],
        emit_project_config: bool,
    ) -> Path:
        """Launch Claude Code integration setup."""
        return self.setup(workspace_root, interaction_path, emit_project_config)

    def ensure_workspace_settings(
        self,
        workspace_root: Path,
        interaction_path: Optional[Path],
        emit_project_config: bool,
    ) -> Path:
        """Write Claude Code settings and optional CLAUDE.md instructions."""
        claude_dir = workspace_root / ".claude"
        claude_dir.mkdir(parents=True, exist_ok=True)

        settings_path = claude_dir / "settings.json"
        settings = self._build_settings(
            workspace_root,
            interaction_path,
            emit_project_config,
        )
        settings_path.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")

        if emit_project_config:
            claude_md_path = workspace_root / "CLAUDE.md"
            claude_md_path.write_text(
                self._render_claude_markdown(workspace_root, interaction_path),
                encoding="utf-8",
            )

        return settings_path

    def emit_project_config(
        self, workspace_root: Path, interaction: Path | None
    ) -> Path:
        """Emit Claude Code project.json configuration."""
        config_dir = workspace_root / ".claude"
        config_dir.mkdir(parents=True, exist_ok=True)
        config_path = config_dir / "project.json"
        payload = {
            "workspace": str(workspace_root),
            "interaction": str(interaction) if interaction else None,
        }
        config_path.write_text(json.dumps(payload, indent=2))
        return config_path

    def _build_settings(
        self,
        workspace_root: Path,
        interaction_path: Optional[Path],
        emit_project_config: bool,
    ) -> dict[str, Any]:
        settings: dict[str, Any] = {
            "project": {
                "root": str(workspace_root),
            }
        }

        if interaction_path is not None:
            settings["project"]["interaction"] = self._relative_path(
                interaction_path,
                workspace_root,
            )

        if emit_project_config:
            settings["project"]["instructions"] = "CLAUDE.md"
        elif interaction_path is not None:
            settings["project"]["instructions"] = self._relative_path(
                interaction_path,
                workspace_root,
            )

        return settings

    def _relative_path(self, path: Path, base: Path) -> str:
        try:
            return str(path.relative_to(base))
        except ValueError:
            return str(path)

    def _render_claude_markdown(
        self,
        workspace_root: Path,
        interaction_path: Optional[Path],
    ) -> str:
        lines = [
            "# Claude Code Workspace",
            "",
            "This file was generated by devman to describe workspace instructions.",
            "",
            f"- Workspace root: `{workspace_root}`",
        ]

        if interaction_path is not None:
            lines.append(
                f"- Interaction guide: `{self._relative_path(interaction_path, workspace_root)}`"
            )

        lines.append("")
        lines.append("Follow the interaction guide for workspace-specific workflows and norms.")
        lines.append("")

        return "\n".join(lines)
